--//====================================================
--// Type Defs (if needed)
--//====================================================

local Example = {}
--//====================================================
--// Imports / Services
--//====================================================

local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local Root = LocalPlayer.PlayerScripts
local ClientModuleDirectory = require(Root.ClientModuleDirectory)

--//====================================================
--// Local Variables / Constants
--//====================================================

local a = 20
local b = 15

--//====================================================
--// Local Function
--//====================================================

return Example