return {
	["100Coins"] = {
		productId = "3417901227",
		cost = 25,
		image = "rbxassetid://87991014507516",
		title = "+100 Coins",
		canBuy = true,
	},
    ["250Coins"] = {
		productId = "3417900833",
		cost = 60,
		image = "rbxassetid://110929942730131",
		title = "+250 Coins",
		canBuy = true,
	},
	["500Coins"] = {
		productId = "3417900635",
		cost = 110,
		image = "rbxassetid://90664445318759",
		title = "+500 Coins",
		canBuy = true,
	},
    ["1000Coins"] = {
		productId = "3417900502",
		cost = 200,
		image = "rbxassetid://107327997366312	",
		title = "+1000 Coins",
		canBuy = true,
	},
}
