return {
	["100Coins"] = {
		productId = "3417901227",
		cost = 25,
		image = "rbxassetid://85873851255829",
		title = "+100 Coins",
		canBuy = true,
	},
    ["250Coins"] = {
		productId = "3417900833",
		cost = 60,
		image = "rbxassetid://85873851255829",
		title = "+250 Coins",
		canBuy = true,
	},
	["500Coins"] = {
		productId = "3417900635",
		cost = 110,
		image = "rbxassetid://134530009673136",
		title = "+500 Coins",
		canBuy = true,
	},
    ["1000Coins"] = {
		productId = "3417900502",
		cost = 200,
		image = "rbxassetid://71702375047150",
		title = "+1000 Coins",
		canBuy = true,
	},
}
