return {
	["1xRespawn"] = {
		productId = "3392425527",
		cost = 10,
		image = "rbxassetid://121852647790789",
		title = "1x Respawn",
	},
    ["3xRespawn"] = {
		productId = "3403987104",
		cost = 25,
		image = "rbxassetid://75123985925746",
		title = "3x Respawn",
	},
    ["5xRespawn"] = {
		productId = "3403989041",
		cost = 40,
		image = "rbxassetid://73927622112008",
		title = "5x Respawn",
	},
}
