local CustomMaterials = {}

CustomMaterials.Materials = {"Sand" , "Mud" , "Grass" , "Obsidian"}

CustomMaterials.Sand = {}
CustomMaterials.Sand.Material = Enum.Material.Sand
CustomMaterials.Sand.Color = Color3.new(0.811765, 0.67451, 0.4)

CustomMaterials.Mud = {}
CustomMaterials.Mud.Material = Enum.Material.Mud
CustomMaterials.Mud.Color = Color3.new(0.333333, 0.215686, 0.207843)

CustomMaterials.Obsidian = {}
CustomMaterials.Obsidian.Color = Color3.fromRGB(98, 37, 209)
CustomMaterials.Obsidian.Material = Enum.Material.CrackedLava

CustomMaterials.Grass = {}
CustomMaterials.Grass.Color = Color3.fromRGB(52, 142, 64)
CustomMaterials.Grass.Material = Enum.Material.Grass

CustomMaterials.Stone = {}
CustomMaterials.Stone.Color = Color3.fromRGB(75, 75, 75)
CustomMaterials.Stone.Material = Enum.Material.Slate

CustomMaterials.Snow = {}
CustomMaterials.Snow.Color = Color3.fromRGB(221, 221, 221)
CustomMaterials.Snow.Material = Enum.Material.Snow

CustomMaterials["Plastic-Yellow"] = {}
CustomMaterials["Plastic-Yellow"].Material = Enum.Material.SmoothPlastic
CustomMaterials["Plastic-Yellow"].Color = Color3.new(0.839216, 0.729412, 0.113725)

CustomMaterials["Plastic-Blue"] = {}
CustomMaterials["Plastic-Blue"].Material = Enum.Material.SmoothPlastic
CustomMaterials["Plastic-Blue"].Color = Color3.new(0.156863, 0.392157, 0.827451)

CustomMaterials["Plastic-Red"] = {}
CustomMaterials["Plastic-Red"].Material = Enum.Material.SmoothPlastic
CustomMaterials["Plastic-Red"].Color = Color3.new(1, 0.282353, 0.188235)

CustomMaterials["Plastic-Green"] = {}
CustomMaterials["Plastic-Green"].Material = Enum.Material.SmoothPlastic
CustomMaterials["Plastic-Green"].Color = Color3.new(0.305882, 0.615686, 0.454902)

CustomMaterials["Pink-Sand"] = {}
CustomMaterials["Pink-Sand"].Material = Enum.Material.Sand
CustomMaterials["Pink-Sand"].Color = Color3.new(0.858824, 0.568627, 0.898039)

CustomMaterials["Sand-Blue"] = {}
CustomMaterials["Sand-Blue"].Material = Enum.Material.Sand
CustomMaterials["Sand-Blue"].Color = Color3.new(0.188235, 0.470588, 1)

CustomMaterials["Sand-Red"] = {}
CustomMaterials["Sand-Red"].Material = Enum.Material.Sand
CustomMaterials["Sand-Red"].Color = Color3.new(0.847059, 0.227451, 0.160784)

CustomMaterials["Sand-Green"] = {}
CustomMaterials["Sand-Green"].Material = Enum.Material.Sand
CustomMaterials["Sand-Green"].Color = Color3.new(0.333333, 0.666667, 0.498039)



return CustomMaterials
